"""Build the browser sound bank from the Astra sound set in assets/audio.

The clips are generated by `node scripts/generate-astra-audio.js --install`
(gameplay) and `node scripts/generate-astra-ui-audio.js --install` (boot, menu
and UI): mono 44.1 kHz PCM16 WAV, loops already seamless and at in-game loudness.
This packs them into sound-bank.js and records their measurements in
manifest.json. Only Python's standard library is needed.
"""
import array
import base64
import hashlib
import json
import math
from pathlib import Path
import sys
import wave

ROOT = Path(__file__).resolve().parents[1]
AUDIO = ROOT / "assets" / "audio"
RATE = 44100
GENERATOR = "scripts/generate-astra-audio.js"
UI_GENERATOR = "scripts/generate-astra-ui-audio.js"
SHOTS = ["intro", "intermission", "death", "fruit", "ghost", "extraLife", "munchA", "munchB", "powerUp", "zap"]
LOOPS = ["siren0", "siren1", "siren2", "siren3", "siren4", "frightened", "returning"]
UI_SHOTS = ["bootIntro", "titleSting", "uiMove", "uiChange", "uiConfirm", "uiBack", "uiClick", "soundOn", "soundOff", "uiBuy",
            "uiEquip", "uiLoadoutAdd", "uiLoadoutRemove", "uiDenied", "tally", "levelUp", "achievement", "gameOver",
            "alarm", "victory", "readyUp"]
UI_LOOPS = ["menuLoop"]


def read(key):
    path = AUDIO / (key + ".wav")
    with wave.open(str(path), "rb") as f:
        assert (f.getnchannels(), f.getsampwidth(), f.getframerate()) == (1, 2, RATE), f"{path}: expected mono 44.1 kHz PCM16"
        data = array.array("h", f.readframes(f.getnframes()))
    if sys.byteorder != "little":
        data.byteswap()
    return path.read_bytes(), data


clips, metadata = {}, {}
for key in SHOTS + LOOPS + UI_SHOTS + UI_LOOPS:
    payload, data = read(key)
    loop = key in LOOPS or key in UI_LOOPS
    duration = len(data) / RATE
    clips[key] = {"duration": duration, "loop": loop, "data": base64.b64encode(payload).decode("ascii")}
    metadata[key] = {"source": "generated:" + (UI_GENERATOR if key in UI_SHOTS + UI_LOOPS else GENERATOR), "frames": len(data), "sampleRate": RATE,
                     "duration": duration, "loopStart": 0 if loop else None, "loopEnd": duration if loop else None,
                     "peak": max(abs(v) for v in data) / 32768,
                     "rms": math.sqrt(sum(v*v for v in data)/len(data)) / 32768,
                     "sha256": hashlib.sha256(payload).hexdigest()}

timings = {"introDuration": math.ceil(clips["intro"]["duration"]*60)/60,
           "intermissionDuration": math.ceil(clips["intermission"]["duration"]*60)/60}
bank = {"version": 2, "timings": timings, "clips": clips}
(ROOT / "sound-bank.js").write_text(
    "/* Astra-Man sound set; generated by " + GENERATOR + " and " + UI_GENERATOR + ", packed by scripts/build-audio.py. */\n"
    "(function(root){\"use strict\";const bank=" + json.dumps(bank, separators=(",", ":")) +
    ";if(typeof module!==\"undefined\"&&module.exports)module.exports=bank;else root.PacmanSoundBank=bank;})(globalThis);\n",
    encoding="utf-8")
(AUDIO / "manifest.json").write_text(json.dumps({"generators": [GENERATOR, UI_GENERATOR], "timings": timings, "clips": metadata}, indent=2)+"\n")
print(json.dumps({"clips": len(clips), "bankBytes": (ROOT/"sound-bank.js").stat().st_size, "timings": timings}))
